apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx-dynamic
  labels:
      nfs-export.csi.k8s.io/id: deployment-nginx-dynamic
spec:
  replicas: 5
  selector:
    matchLabels:
      nfs-export.csi.k8s.io/id: deployment-nginx-dynamic
  strategy:
    type: Recreate
  template:
    metadata:
      name: deployment-nginx-dynamic
      labels:
        nfs-export.csi.k8s.io/id: deployment-nginx-dynamic
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      terminationGracePeriodSeconds: 0
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - deployment-nginx-dynamic
            topologyKey: topology.kubernetes.io/hostname
      containers:
        - name: deployment-nginx-dynamic
          image: daocloud.io/nginx
          imagePullPolicy: IfNotPresent
          resources: {}
          command:
            - "/bin/bash"
            - "-c"
            - set -euo pipefail; while true; do echo $(hostname) $(date) >> /data/outfile; sleep 1; done
          volumeMounts:
            - name: data
              mountPath: "/data"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-nfs-export-dynamic
