
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nfs-client
  strategy:
    type: Recreate
  template:
    metadata:
      name: nfs-client
      labels:
        name: nfs-client
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: nfs-client
          image: d3fk/nfs-client
          securityContext:
            privileged: true
          command:
            - tail
            - -f
            - /dev/null 