kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-export-static
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-export
  storageClassName: csi-nfs-export
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-export
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-nfs-export
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs-export.csi.k8s.io
    volumeHandle: nfs-d4aeb932-5403-40ed-9e0e-f60639ef6ebe # generate by uuigen
    volumeAttributes:
      dataVolumeClaim: pvc-local
      dataNamespace: default
  
