---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-export-static
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-export
  storageClassName: nfs-export-csi
